spring:
  application:
    name: Bootstrap Spring Boot
  datasource:
    url: jdbc:mysql://localhost:3306/scheduler
    username: "root"
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  mvc:
    contentnegotiation:
      favor-path-extension: false
      favor-parameter: false
      media-types:
        json: application/json
logging:
  level:
    root: INFO
